# Generated by Django 3.2.8 on 2021-10-19 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 15, 42, 57, 433410, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
